ENT.Base = "base_gmodentity"
ENT.Type = "anim"
ENT.PrintName = "Large Health Pack"
ENT.Author = "Kiddley"
ENT.Purpose = "A large health pack that restores 100% of the entity that touches it's max HP."
ENT.Instructions = "Use the entity to open the weapon selector GUI"
ENT.Spawnable = true
ENT.AdminSpawnable = true
ENT.Category = "Garry's Modular Combat"
ENT.Icon = "vgui/entities/gmc_largemedkiticon.vtf"